//To combine both text and a variable, use the + character:

String name = "John";
System.out.println("Hello " + name);

//You can also use the + character to add a variable to another variable:

String firstName = "John ";
String lastName = "Doe";
String fullName = firstName + lastName;
System.out.println(fullName);

//For numeric values, the + character works as a mathematical operator

int x = 5;
int y = 6;
System.out.println(x + y); // Print the value of x + y
